//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> StratDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Url { get; set; }
    
        public virtual User User { get; set; }
    }
}
